# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: luka3989

development:
  adapter: mysql2
  encoding: utf8
  database: TWINS_COM
  pool: 5
  username: root
  password: luka3989
  host: localhost
  #<<: *default
  #database: db/development.sqlite3

