# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Fh4xli2uTF

development:
  adapter: mysql2
  encoding: utf8
  database: POST_APP
  pool: 5
  username: root
  password: Fh4xli2uTF
  host: localhost



